---
output_level: debug
prefs:
  ap: AP
  epg: EPG
  vrf: VRF
  bd: BD
# Let's suffixes to a tenant's discretion. We manage only prefixes on tenant name:
tnn: '{{ pref }}{{ tn }}'
aps:
  "a": # Aplication profile (AP) level, assuming one VRF per Tn. Need more or route-leaking, use VRFs from common.
    "1": # End-point groupe (EPG) level, assuming no BD sharing.
      #type: untagged access port by default
      dom: "1"
      phy: "a1"
      msk: 24
      gw: 192.168.1.1
      role: provider
      tst: "1" # not used in prd
    "2":
      #type: untagged access port by default
      dom: "1"
      phy: "a2"
      msk: 24
      gw: 192.168.2.1
      role: consumer
      tst: "2" # not used in prd
tsts:
  "1":
    pap: a
    pepg: "2"
    ip: 192.168.1.11
  "2":
    pap: a
    pepg: "1"
    ip: 192.168.2.11
